#!/bin/bash
#
# The configuration that exists nowhere else.
#
# The site itself is in git and regenerated by a build, so it is not backed up
# here — what is, is the state that only lives on this box: TLS keys, the nginx
# and firewall configuration, the fail2ban jails, the sshd hardening, and the
# scripts in /usr/local/sbin.
#
# **This is a local backup.** It restores a box you have broken; it does not
# restore a box you have lost. Copying these off-site needs a destination and a
# credential, which is a decision for the owner rather than something to invent.
# Losing everything is survivable — the certificate can be reissued and the rest
# is described in the repository's infra/ directory — but it would be a slow
# afternoon rather than a restore.
set -euo pipefail
dest=/var/backups/oda
stamp=$(date -u +%Y-%m-%dT%H%M%SZ)
file="$dest/config-$stamp.tar.gz"

tar -czf "$file" \
  -C / etc/letsencrypt etc/nginx etc/ufw etc/fail2ban etc/ssh/sshd_config.d \
       etc/sysctl.d/99-hardening.conf usr/local/sbin 2>/dev/null

# Contains private keys. Readable by root and nobody else, and never anywhere
# nginx can serve from.
chmod 600 "$file"

# Keep a fortnight. Enough to notice a bad change and go back past it.
ls -1t "$dest"/config-*.tar.gz 2>/dev/null | tail -n +15 | xargs -r rm -f

logger -t oda-backup "wrote $(basename "$file") ($(du -h "$file" | cut -f1)), $(ls -1 "$dest"/config-*.tar.gz | wc -l) kept"
