#!/bin/bash
#
# Everything on this box that exists nowhere else.
#
# Two archives, because they are two different kinds of loss and one of them
# contains other people's data.
#
#   config-*  TLS keys, nginx, ufw, fail2ban, sshd hardening, /usr/local/sbin.
#             The site itself is in git and regenerated by a build, so it is not
#             here.
#
#   tickets-* the report database and the attachments on it. **This was missing
#             entirely.** The backup covered the configuration and left the only
#             irreplaceable thing on the box — strangers' support reports and the
#             screenshots they sent — with no copy at all. Configuration can be
#             rebuilt from the repository in an afternoon; a report somebody sent
#             about a stolen inventory cannot be rebuilt from anything.
#
# **Both are local.** They restore a box you have broken; they do not restore a
# box you have lost. Copying them off-site needs a destination and a credential,
# which is the owner's decision rather than something to invent — see
# infra/README.md.
set -euo pipefail
dest=/var/backups/oda
stamp=$(date -u +%Y-%m-%dT%H%M%SZ)

mkdir -p "$dest"

# ── configuration ────────────────────────────────────────────────────────────
config="$dest/config-$stamp.tar.gz"
tar -czf "$config" \
  -C / etc/letsencrypt etc/nginx etc/ufw etc/fail2ban etc/ssh/sshd_config.d \
       etc/sysctl.d/99-hardening.conf usr/local/sbin 2>/dev/null

# Contains private keys. Readable by root and nobody else, and never anywhere
# nginx can serve from.
chmod 600 "$config"

# ── reports and attachments ──────────────────────────────────────────────────
#
# `VACUUM INTO` rather than copying the file. SQLite runs in WAL mode here, so
# recent commits live in a separate -wal file and copying tickets.db alone can
# capture a database missing exactly the reports that arrived most recently — a
# backup that restores cleanly while being quietly short of the newest data is
# worse than one that fails loudly.
#
# Driven through node rather than the sqlite3 CLI, which is not installed on this
# box and is not worth installing for one statement: the service already depends
# on node's own SQLite, so the backup uses the same engine that wrote the file.
tickets="$dest/tickets-$stamp.tar.gz"
if [ -f /var/lib/tickets/tickets.db ]; then
  snapshot=$(mktemp -d)
  # Owned by the service account, because the snapshot is *written* by it. The
  # first version left this root-owned at mode 700 and the vacuum failed with
  # "unable to open database file" — the read permission was the obvious half of
  # the problem and the write permission was the half that actually bit.
  chmod 700 "$snapshot"
  chown tickets:tickets "$snapshot"
  # `runuser`, not `sudo`. The unit sets `NoNewPrivileges=true`, which blocks the
  # setuid transition sudo relies on — it fails with "error initializing audit
  # plugin". runuser is the tool for dropping privilege when already root, and it
  # needs no setuid at all, so the hardening stays on.
  #
  # As the owning user either way: the WAL has to be readable, and nothing
  # root-owned should be left behind in /var/lib/tickets.
  runuser -u tickets -- node --input-type=module -e "
    const { DatabaseSync } = await import('node:sqlite');
    const db = new DatabaseSync('/var/lib/tickets/tickets.db', { readOnly: true });
    db.exec(\"VACUUM INTO '$snapshot/tickets.db'\");
    db.close();
  "
  tar -czf "$tickets" -C "$snapshot" tickets.db \
      -C /var/lib/tickets attachments 2>/dev/null
  rm -rf "$snapshot"
  chmod 600 "$tickets"
else
  tickets=""
fi

# ── retention ────────────────────────────────────────────────────────────────
#
# A fortnight of configuration: enough to notice a bad change and go back past
# it. Reports are kept 90 days to match the retention the privacy page states —
# holding backups of deleted reports for longer than the reports themselves
# would make that promise false.
ls -1t "$dest"/config-*.tar.gz 2>/dev/null | tail -n +15 | xargs -r rm -f
find "$dest" -name 'tickets-*.tar.gz' -mtime +90 -delete 2>/dev/null || true

kept_config=$(ls -1 "$dest"/config-*.tar.gz 2>/dev/null | wc -l)
kept_tickets=$(ls -1 "$dest"/tickets-*.tar.gz 2>/dev/null | wc -l)
if [ -n "$tickets" ]; then
  logger -t oda-backup "config $(du -h "$config" | cut -f1) ($kept_config kept), tickets $(du -h "$tickets" | cut -f1) ($kept_tickets kept)"
else
  logger -t oda-backup "config $(du -h "$config" | cut -f1) ($kept_config kept), no ticket database yet"
fi
